"""Build the static leaderboard page from committed benchmark results.

A pure function of the repo: scans benchmark/results/*/summary.json (+ the
manifest for provenance), renders one no-JS single-file HTML page into
benchmark/leaderboard/index.html. Re-run any time; commit the output.
(Staged copy; lands as scripts/build_leaderboard.py.)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from xml.sax.saxutils import escape

AXES = ("definitional", "grain", "ambiguity", "refusal", "faithfulness")


def build(results_dir: Path, out_path: Path) -> Path:
    """Render the leaderboard from every summary.json under ``results_dir``."""
    rows = []
    for summary_path in sorted(results_dir.glob("*/summary.json")):
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        manifest = json.loads((summary_path.parent / "manifest.json").read_text(encoding="utf-8"))
        rows.append((summary, manifest))

    def pct(x: float) -> str:
        return f"{x * 100:.1f}%"

    body = []
    for summary, manifest in rows:
        axes_cells = "".join(
            f"<td>{pct(summary['per_axis'][a]) if a in summary['per_axis'] else '—'}</td>"
            if not (
                a == "faithfulness" and "judge" in summary and "not evaluated" in summary["judge"]
            )
            else "<td title='not evaluated offline'>n/e</td>"
            for a in AXES
        )
        body.append(
            "<tr>"
            f"<td><strong>{escape(summary['agent'])}</strong></td>"
            f"<td>{escape(summary['condition'])}</td>"
            f"<td>{pct(summary['ran_fine'])}</td>"
            f"<td><strong>{pct(summary['business_correct'])}</strong></td>"
            f"<td>{pct(summary['overall_weighted'])}</td>"
            f"{axes_cells}"
            f"<td><code>{escape(manifest['suite_hash'])}</code> · "
            f"seeds {escape(','.join(str(s) for s in manifest['seeds']))} · "
            f"${manifest['totals']['cost_usd']:.2f}</td>"
            "</tr>"
        )

    pending = """
    <tr class="pending"><td colspan="11">Frontier agent rows (Anthropic / OpenAI APIs,
    closed + open book, 3 seeds) are pending keyed runs — every number on this page is
    traceable to a committed manifest, and none will be projected in advance.
    Private-split numbers appear only as aggregates when published
    (<a href="https://github.com/kartikeyamandhar/ledgerbench/blob/main/docs/private-split.md">protocol</a>).</td></tr>
    """

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>LedgerBench leaderboard</title>
<style>
 body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 2rem auto;
        max-width: 1080px; color: #212121; line-height: 1.5; }}
 table {{ border-collapse: collapse; width: 100%; font-size: 0.88rem; }}
 th, td {{ text-align: left; padding: 7px 10px; border-bottom: 1px solid #e0e0e0; }}
 th {{ background: #fafafa; }}
 .pending td {{ color: #616161; font-size: 0.82rem; background: #fffde7; }}
 code {{ background: #f5f5f5; border-radius: 4px; padding: 1px 4px; }}
 .note {{ color: #616161; font-size: 0.85rem; }}
</style></head><body>
<h1>LedgerBench — are analytics agents business-correct?</h1>
<p>Execution success is not business correctness. Each row: one agent, one condition
(closed book = schema only; open book = schema + the business rulebook), 3 seeds over
the 150-item public bank. <strong>Per-axis numbers always appear beside the
aggregate</strong>; weights are printed in every run report.</p>
<table>
<tr><th>agent</th><th>condition</th><th>ran fine</th><th>business-correct</th>
<th>weighted overall</th><th>definitional</th><th>grain</th><th>ambiguity</th>
<th>refusal</th><th>faithfulness</th><th>provenance</th></tr>
{"".join(body)}
{pending}
</table>
<p class="note">The <code>naive</code> rows are the deterministic offline floor: a
keyword-template baseline that answers everything and reads nothing. Its identical
closed/open scores demonstrate the floor ignores the rulebook — the gap the benchmark
measures. Generated by <code>scripts/build_leaderboard.py</code> from
<code>benchmark/results/</code>; every number is recomputable from committed traces.</p>
</body></html>
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cleaned = "\n".join(line.rstrip() for line in html.splitlines()) + "\n"
    out_path.write_text(cleaned, encoding="utf-8")
    return out_path


if __name__ == "__main__":
    results = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("benchmark/results")
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("benchmark/leaderboard/index.html")
    print(build(results, out))
